name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: setup submodule
      run: git submodule init
      
    - name: sync submodules
      run: git submodule update

    - name: Build
      run: make
